'use strict';

const META_KEY = 'dmforge-backup-meta-v1';
const EXCLUDED_KEYS = new Set([META_KEY, 'dmforge-pending-encounter-v1']);
const MAX_IMPORT_BYTES = 50 * 1024 * 1024;

const TOOLS = [
  { key:'dmforge-shared-v1', label:'Campaign Hub', route:'campaigns.html', description:'Campaign names and safe cross-tool summaries.', summarize:(data)=>({count:data?.campaigns?.length||0,text:`${data?.campaigns?.length||0} campaign${data?.campaigns?.length===1?'':'s'}`}) },
  { key:'dmforge-session-console-v1', label:'Session Console', route:'session-console.html', description:'Session prep, logs, archives, rosters, initiative, dice, and generators.', summarize:(data)=>{const campaigns=Array.isArray(data?.campaigns)?data.campaigns:[];const archives=campaigns.reduce((sum,campaign)=>sum+(campaign.archives?.length||0),0);return{count:campaigns.length+archives,text:`${campaigns.length} campaign${campaigns.length===1?'':'s'} · ${archives} archive${archives===1?'':'s'}`};} },
  { key:'dmforge-encounter-forge-v1', label:'Encounter Forge', route:'encounter-forge.html', description:'Party profiles, saved encounters, and custom monsters.', summarize:(data)=>({count:(data?.encounters?.length||0)+(data?.profiles?.length||0),text:`${data?.encounters?.length||0} encounter${data?.encounters?.length===1?'':'s'} · ${data?.profiles?.length||0} party profile${data?.profiles?.length===1?'':'s'}`}) },
  { key:'dmforge-npc-forge-v1', label:'NPC Forge', route:'npc-forge.html', description:'NPC identities, motives, secrets, relationships, and combat notes.', summarize:(data)=>{const list=Array.isArray(data)?data:Array.isArray(data?.npcs)?data.npcs:[];return{count:list.length,text:`${list.length} NPC${list.length===1?'':'s'}`};} },
  { key:'dmforge-loot-forge-v1', label:'Loot Forge', route:'loot-forge.html', description:'Treasure parcels, distribution, private notes, and magic candidates.', summarize:(data)=>{const list=Array.isArray(data)?data:Array.isArray(data?.parcels)?data.parcels:[];return{count:list.length,text:`${list.length} treasure parcel${list.length===1?'':'s'}`};} },
  { key:'dmforge-magic-items-v2', label:'Magic Item Forge', route:'magic-items.html', description:'Magic-item cards, hidden properties, artwork, identification, and stages.', summarize:(data)=>{const list=Array.isArray(data)?data:[];return{count:list.length,text:`${list.length} magic item${list.length===1?'':'s'}`};} },
  { key:'dmforge-player-display-rooms-v1', label:'Player Display', route:'player-display.html', description:'Remembered Player Display room codes.', summarize:(data)=>{const count=data&&typeof data==='object'?Object.keys(data).length:0;return{count,text:`${count} remembered room${count===1?'':'s'}`};} }
];

const $ = (selector) => document.querySelector(selector);
let pendingImport = null;

function esc(value){return String(value??'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[character]);}
function bytesOf(value){return new TextEncoder().encode(String(value??'')).byteLength;}
function humanBytes(bytes){const value=Number(bytes)||0;if(value<1024)return`${value} B`;const units=['KB','MB','GB'];let amount=value/1024;let unit=units[0];for(let index=1;index<units.length&&amount>=1024;index+=1){amount/=1024;unit=units[index];}return`${amount.toFixed(amount>=10?1:2)} ${unit}`;}
function formatDate(value){if(!value)return'No date available';return new Date(value).toLocaleString([],{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
function readMeta(){try{return JSON.parse(localStorage.getItem(META_KEY)||'null')||{};}catch{return{};}}
function writeMeta(patch){localStorage.setItem(META_KEY,JSON.stringify({...readMeta(),...patch}));}
function acceptedKey(key){return!EXCLUDED_KEYS.has(key)&&(/^dmforge-[a-z0-9-]+$/i.test(key)||/^cleric-box-[a-z0-9]+$/i.test(key));}
function allBackupKeys(){const keys=[];for(let index=0;index<localStorage.length;index+=1){const key=localStorage.key(index);if(key&&acceptedKey(key))keys.push(key);}return keys.sort();}
function parseRecord(raw){if(raw==null)return{exists:false,valid:true,data:null,error:''};try{return{exists:true,valid:true,data:JSON.parse(raw),error:''};}catch(error){return{exists:true,valid:false,data:null,error:error.message};}}
function newestTimestamp(value,newest=null){if(Array.isArray(value)){value.forEach((entry)=>{newest=newestTimestamp(entry,newest);});return newest;}if(!value||typeof value!=='object')return newest;for(const[key,entry]of Object.entries(value)){if(/^(updatedAt|archivedAt|createdAt|exportedAt)$/i.test(key)&&typeof entry==='string'){const time=Date.parse(entry);if(Number.isFinite(time)&&(!newest||time>newest))newest=time;}else if(entry&&typeof entry==='object')newest=newestTimestamp(entry,newest);}return newest;}

function clericRecord(){const keys=allBackupKeys().filter((key)=>key.startsWith('cleric-box-'));const raws=keys.map((key)=>localStorage.getItem(key)||'');const parsed=raws.map(parseRecord);const valid=parsed.every((entry)=>entry.valid);return{label:'Cleric in a Box',route:'https://cbw29512.github.io/healingbox/',description:'Artifact rooms, charges, settings, and activity history.',keys,bytes:raws.reduce((sum,raw)=>sum+bytesOf(raw),0),count:keys.length,summary:`${keys.length} saved artifact room${keys.length===1?'':'s'}`,valid,newest:parsed.reduce((time,entry)=>entry.valid?newestTimestamp(entry.data,time):time,null),error:valid?'':'One or more room records could not be read.'};}
function unknownRecord(){const known=new Set(TOOLS.map((tool)=>tool.key));const keys=allBackupKeys().filter((key)=>key.startsWith('dmforge-')&&!known.has(key));const raws=keys.map((key)=>localStorage.getItem(key)||'');const parsed=raws.map(parseRecord);return{label:'Other DM Forge Data',route:'',description:'Additional versioned DM Forge records.',keys,bytes:raws.reduce((sum,raw)=>sum+bytesOf(raw),0),count:keys.length,summary:`${keys.length} additional record${keys.length===1?'':'s'}`,valid:parsed.every((entry)=>entry.valid),newest:parsed.reduce((time,entry)=>entry.valid?newestTimestamp(entry.data,time):time,null),error:parsed.every((entry)=>entry.valid)?'':'One or more additional records could not be read.'};}
function toolRecords(){const records=TOOLS.map((tool)=>{const raw=localStorage.getItem(tool.key);const parsed=parseRecord(raw);let summary={count:0,text:'No saved data yet'};if(parsed.exists&&parsed.valid){try{summary=tool.summarize(parsed.data);}catch(error){parsed.valid=false;parsed.error=error.message;}}return{...tool,keys:[tool.key],bytes:raw==null?0:bytesOf(raw),count:summary.count,summary:summary.text,valid:parsed.valid,exists:parsed.exists,newest:parsed.valid?newestTimestamp(parsed.data):null,error:parsed.error};});const cleric=clericRecord();const unknown=unknownRecord();records.push({...cleric,exists:cleric.keys.length>0});if(unknown.keys.length)records.push({...unknown,exists:true});return records;}
function statusFor(record){if(!record.valid)return{className:'bad',text:'Needs recovery'};if(!record.exists)return{className:'warning',text:'No saved data'};return{className:'',text:'Saved safely'};}
function renderStorage(records){$('#storageGrid').innerHTML=records.map((record)=>{const status=statusFor(record);const classes=['storage-card',!record.valid?'invalid':'',!record.exists?'empty':''].filter(Boolean).join(' ');const action=record.route?`<a class="btn light" href="${esc(record.route)}"${record.route.startsWith('http')?' target="_blank" rel="noopener"':''}>Open Tool</a>`:'';return`<article class="${classes}"><span class="status-pill ${status.className}">${status.text}</span><h3>${esc(record.label)}</h3><p>${esc(record.description)}</p><div class="storage-meta"><div><b>${esc(record.summary)}</b><span>Saved records</span></div><div><b>${humanBytes(record.bytes)}</b><span>Local size</span></div><div><b>${formatDate(record.newest)}</b><span>Newest change</span></div></div>${record.error?`<p class="status-pill bad">${esc(record.error)}</p>`:''}<div class="actions">${action}</div></article>`;}).join('');}

async function renderQuota(){if(!navigator.storage?.estimate)return;try{const estimate=await navigator.storage.estimate();$('#quotaUsed').textContent=humanBytes(estimate.usage||0);$('#quotaTotal').textContent=estimate.quota?`of approximately ${humanBytes(estimate.quota)} available`:'Browser did not report a limit.';}catch(error){console.warn('[ProtectMyCampaign]',error.message);}}
function renderMeta(){const meta=readMeta();if(!meta.lastBackupAt)return;const time=Date.parse(meta.lastBackupAt);$('#lastBackup').textContent=formatDate(time);const days=Math.floor((Date.now()-time)/86400000);$('#backupAge').textContent=days<=0?'Safety Copy downloaded today.':`${days} day${days===1?'':'s'} since the last Safety Copy.`;}

async function renderRecoveryHistory(){const listElement=$('#recoveryList');const manager=window.DMForgeRecovery;if(!manager){$('#recoveryCount').textContent='Unavailable';$('#recoveryNewest').textContent='This browser cannot create automatic recovery points.';listElement.innerHTML='<article class="recovery-empty">Automatic recovery is unavailable in this browser. You can still download a Safety Copy.</article>';return;}try{const points=await manager.list();$('#recoveryCount').textContent=String(points.length);$('#recoveryNewest').textContent=points.length?`Newest: ${formatDate(points[0].createdAt)}`:'A recovery point will appear after you save campaign data.';if(!points.length){listElement.innerHTML='<article class="recovery-empty">No recovery points yet. DM Forge creates them automatically after campaign data is saved.</article>';return;}listElement.innerHTML=points.map((point)=>`<article class="recovery-card"><div><h3>${esc(point.reason||'Recovery point')}</h3><p>${formatDate(point.createdAt)} · ${point.entryCount} protected data set${point.entryCount===1?'':'s'} · ${humanBytes(point.bytes)}</p></div><div class="actions"><button class="btn light" type="button" data-restore-point="${esc(point.id)}">Restore</button><button class="btn light" type="button" data-delete-point="${esc(point.id)}">Remove</button></div></article>`).join('');}catch(error){console.error(error);$('#recoveryCount').textContent='Needs attention';$('#recoveryNewest').textContent=error.message;listElement.innerHTML=`<article class="recovery-empty">Recovery history could not be opened: ${esc(error.message)}</article>`;}}

async function ensureAutomaticRecovery(){if(!allBackupKeys().length||!window.DMForgeRecovery)return;try{await window.DMForgeRecovery.create('Automatic recovery point',{automatic:true});}catch(error){console.warn('[ProtectMyCampaign]',error.message);}}
async function scan(){const records=toolRecords();renderStorage(records);const keys=allBackupKeys();const totalBytes=keys.reduce((sum,key)=>sum+bytesOf(localStorage.getItem(key)||''),0);const totalRecords=records.reduce((sum,record)=>sum+(record.count||0),0);const invalid=records.filter((record)=>!record.valid);$('#totalBytes').textContent=humanBytes(totalBytes);$('#recordCount').textContent=`${totalRecords} summarized record${totalRecords===1?'':'s'} across ${keys.length} saved data set${keys.length===1?'':'s'}`;$('#backupHeadline').textContent=keys.length?`${totalRecords||keys.length} campaign record${(totalRecords||keys.length)===1?' is':'s are'} protected on this device.`:'No DM Forge campaign data is saved on this browser yet.';$('#backupSummary').textContent=keys.length?'DM Forge saves changes automatically and keeps recent local recovery points.':'Create a campaign or record in any DM Forge tool and automatic protection will begin.';$('#recoveryStatus').textContent=invalid.length?'Attention needed':'Healthy';$('#recoveryMessage').textContent=invalid.length?`${invalid.length} saved data set${invalid.length===1?'':'s'} could not be read.`:'All recognized saved records can be read.';await renderQuota();renderMeta();await ensureAutomaticRecovery();await renderRecoveryHistory();}

async function sha256(text){if(!crypto.subtle)return'';const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,'0')).join('');}
async function buildBackup(){const entries={};for(const key of allBackupKeys()){const value=localStorage.getItem(key);if(typeof value!=='string')continue;entries[key]={value,bytes:bytesOf(value),sha256:await sha256(value)};}return{product:'DM Forge Full Local Backup',version:1,displayName:'DM Forge Safety Copy',exportedAt:new Date().toISOString(),origin:location.origin,entryCount:Object.keys(entries).length,entries};}
function downloadJson(data,filename){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
async function downloadBackup(){const button=$('#downloadBackup');button.disabled=true;button.textContent='Preparing Safety Copy…';try{const backup=await buildBackup();if(!backup.entryCount)throw new Error('There is no DM Forge campaign data to protect yet.');const stamp=new Date().toISOString().slice(0,10);downloadJson(backup,`dm-forge-safety-copy-${stamp}.json`);writeMeta({lastBackupAt:backup.exportedAt,lastBackupEntries:backup.entryCount});toast('Safety Copy downloaded. Keep it somewhere private.');await scan();}catch(error){console.error(error);alert(`Safety Copy failed: ${error.message}`);}finally{button.disabled=false;button.textContent='Download Safety Copy';}}

async function validateBackup(parsed){if(parsed?.product!=='DM Forge Full Local Backup'||parsed?.version!==1||!parsed.entries||typeof parsed.entries!=='object')throw new Error('This is not a supported DM Forge Safety Copy.');const entries=[];for(const[key,record]of Object.entries(parsed.entries)){if(!acceptedKey(key))throw new Error(`The Safety Copy contains an unsupported record: ${key}`);if(!record||typeof record.value!=='string')throw new Error('One record in the Safety Copy is damaged.');if(record.value.length>MAX_IMPORT_BYTES)throw new Error('One record is larger than the safety limit.');if(record.sha256){const actual=await sha256(record.value);if(actual&&actual!==record.sha256)throw new Error('The Safety Copy failed its integrity check.');}entries.push({key,value:record.value,bytes:bytesOf(record.value)});}if(!entries.length)throw new Error('The Safety Copy contains no campaign records.');return entries;}
function labelForKey(key){return TOOLS.find((tool)=>tool.key===key)?.label||(key.startsWith('cleric-box-')?'Cleric in a Box':'Other DM Forge Data');}
function showImport(entries,metadata){pendingImport={entries,metadata};const grouped=new Map();for(const entry of entries){const label=labelForKey(entry.key);grouped.set(label,(grouped.get(label)||0)+entry.bytes);}$('#importSummary').innerHTML=`<div class="import-row"><b>Safety Copy created</b><span>${esc(formatDate(Date.parse(metadata.exportedAt)))}</span></div><div class="import-row"><b>Protected areas</b><span>${grouped.size}</span></div><div class="import-row"><b>Total size</b><span>${humanBytes(entries.reduce((sum,entry)=>sum+entry.bytes,0))}</span></div>`+[...grouped.entries()].map(([label,bytes])=>`<div class="import-row"><b>${esc(label)}</b><span>${humanBytes(bytes)}</span></div>`).join('');$('#confirmRestore').checked=false;$('#applyImport').disabled=true;$('#importPanel').hidden=false;$('#importPanel').scrollIntoView({behavior:'smooth',block:'start'});}
async function importFile(file){if(!file)return;if(file.size>MAX_IMPORT_BYTES)return alert('That Safety Copy is larger than the 50 MB safety limit.');try{const parsed=JSON.parse(await file.text());const entries=await validateBackup(parsed);showImport(entries,parsed);}catch(error){console.error(error);alert(`Safety Copy could not be opened: ${error.message}`);}finally{$('#importBackup').value='';}}
function cancelImport(){pendingImport=null;$('#importPanel').hidden=true;$('#confirmRestore').checked=false;$('#applyImport').disabled=true;}
async function applyImport(){if(!pendingImport||!$('#confirmRestore').checked)return;const button=$('#applyImport');button.disabled=true;button.textContent='Restoring…';try{if(window.DMForgeRecovery)await window.DMForgeRecovery.create('Before restoring a Safety Copy',{force:true});for(const entry of pendingImport.entries)localStorage.setItem(entry.key,entry.value);writeMeta({lastRestoreAt:new Date().toISOString(),restoredFrom:pendingImport.metadata.exportedAt||''});const count=pendingImport.entries.length;cancelImport();alert(`${count} protected area${count===1?' was':'s were'} restored. DM Forge will reload now.`);location.reload();}catch(error){console.error(error);alert(`Restore failed: ${error.message}`);button.disabled=false;button.textContent='Restore This Safety Copy';}}

async function createManualRecovery(){const button=$('#manualRecovery');button.disabled=true;button.textContent='Saving…';try{if(!window.DMForgeRecovery)throw new Error('Automatic recovery is unavailable in this browser.');const record=await window.DMForgeRecovery.create('Manual recovery point',{force:true});if(!record)throw new Error('There is no campaign data to save yet.');toast('Recovery point saved on this device.');await renderRecoveryHistory();}catch(error){alert(error.message);}finally{button.disabled=false;button.textContent='Save Recovery Point';}}
async function restoreRecoveryPoint(id){if(!window.DMForgeRecovery)return;if(!confirm('Restore this earlier version? Your current version will be saved first.'))return;try{await window.DMForgeRecovery.restore(id);alert('Earlier version restored. DM Forge will reload now.');location.reload();}catch(error){console.error(error);alert(`Recovery failed: ${error.message}`);}}
async function deleteRecoveryPoint(id){if(!window.DMForgeRecovery||!confirm('Remove this recovery point?'))return;try{await window.DMForgeRecovery.remove(id);await renderRecoveryHistory();}catch(error){alert(`Could not remove recovery point: ${error.message}`);}}
function toast(message){const element=document.createElement('div');element.textContent=message;element.setAttribute('role','status');element.style='position:fixed;z-index:150;left:50%;bottom:20px;transform:translateX(-50%);background:#281713;color:#fff4ce;padding:12px 18px;border:1px solid #d4a64c;border-radius:8px;max-width:90vw;box-shadow:0 8px 30px #0008';document.body.append(element);setTimeout(()=>element.remove(),3500);}

$('#refreshScan').onclick=scan;
$('#manualRecovery').onclick=createManualRecovery;
$('#downloadBackup').onclick=downloadBackup;
$('#importBackup').onchange=(event)=>importFile(event.target.files?.[0]);
$('#cancelImport').onclick=cancelImport;
$('#confirmRestore').onchange=(event)=>{$('#applyImport').disabled=!event.target.checked;};
$('#applyImport').onclick=applyImport;
$('#recoveryList').addEventListener('click',(event)=>{const restore=event.target.closest('[data-restore-point]');const remove=event.target.closest('[data-delete-point]');if(restore)restoreRecoveryPoint(restore.dataset.restorePoint);if(remove)deleteRecoveryPoint(remove.dataset.deletePoint);});
window.addEventListener('storage',scan);
window.addEventListener('dmforge:recovery-changed',renderRecoveryHistory);
scan();
