'use strict';
const KEY='dmforge-magic-items-v2';
const LEGACY_KEY='dmforge-magic-items-v1';
const form=document.getElementById('itemForm');
const preview=document.getElementById('preview');
const libraryGrid=document.getElementById('libraryGrid');
const printSheet=document.getElementById('printSheet');
const campaignFilter=document.getElementById('campaignFilter');
let library=loadLibrary();
let editingId=null;
let previewMode='player-front';
let artworkData='';

const CLERIC_BOX={
  id:'showcase-cleric-in-a-box',name:'Cleric in a Box',template:'artifact',category:'Wondrous Item',rarity:'Unique Artifact',attunement:'No attunement required',ruleset:'Homebrew',campaign:'Showcase Items',owner:'The Party',identification:'identified',unidentifiedName:'Reinforced Divine Chest',unidentifiedText:'A reinforced field chest engraved with symbols that shift to resemble the faith of whoever studies it.',partialProperties:'Divine Provision: The chest contains a renewable reserve of healing magic and cleric scrolls.',icon:'🧰',artData:'',appearance:'A reinforced field chest roughly the size of a modified bag of holding. Golden script moves across its dark wood whenever a divine charge is spent.',description:'Bestowed directly by a campaign deity so the party never loses its adventure to an empty healer’s chair. The box is semi-sentient and acts on the party’s chosen command.',properties:'Divine Charge Matrix: At the end of a long rest, the box manifests divine charges equal to the normal spell slots of a cleric whose level equals the party’s chosen average level.\nPotion Manifestation: A charge may become its linked healing potion. The box rolls the potion’s normal healing dice and the players apply the result.\nScroll Manifestation: A charge may instead become one cleric scroll of that exact spell level. No upcasting or higher-level substitution is allowed.\nSelf-Reading Scrolls: The box produces and reads its own chosen scroll as a free action; no creature needs to hold it or possess Spellcasting.\nShared Resource: Potion and scroll use draw from the same individual charges. Once spent, a charge cannot be used again until restored.\nLong-Rest Restoration: Every spent divine charge returns when the party completes a long rest.\nInviolable Presence: The box cannot be stolen, lost, abandoned, traded, sold, destroyed, damaged, dispelled, suppressed, banished, restrained, imprisoned, possessed, copied, silenced, deceived, altered, or separated from its party by any mortal, immortal, artifact, planar effect, wish, or divine power.',activation:'Free action chosen by a party member; the artifact performs the effect',charges:'One exact-level charge per cleric spell slot at the configured party level',recharge:'All charges return after the party completes a long rest',damage:'Varies by chosen potion or cleric scroll',save:'Uses the DM-approved artifact spell save DC or the chosen spell’s normal resolution',stage:'none',dormantProperties:'',awakenedProperties:'',exaltedProperties:'',backText:'Use the live Cleric in a Box tracker to select a potion or exact-level cleric scroll. Greyed-out charges are unavailable until the next long rest.',secret:'Only the specific deity that granted the artifact can alter, revoke, suppress, or redefine it. That deity is controlled exclusively by the Dungeon Master.'
};

function esc(value){return String(value??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function id(){return crypto.randomUUID?crypto.randomUUID():`item-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function loadLibrary(){try{const current=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(current))return current;const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||'[]');if(Array.isArray(legacy)){const migrated=legacy.map(item=>normalize(item));localStorage.setItem(KEY,JSON.stringify(migrated));return migrated}}catch(error){console.error(error)}return[]}
function normalize(item){return{identification:'identified',unidentifiedName:'Unidentified Item',unidentifiedText:item.appearance||'',partialProperties:'',stage:'none',dormantProperties:'',awakenedProperties:'',exaltedProperties:'',backText:'Keep this card with your character sheet.',artData:'',...item,id:item.id||id()}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(library))}catch(error){alert('The browser could not save this library, usually because uploaded artwork used too much storage. Export your library, then remove or shrink some images.');throw error}}
function values(){return normalize({...Object.fromEntries(new FormData(form).entries()),artData:artworkData,id:editingId||id(),updatedAt:Date.now()})}
function lines(text){return String(text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean)}
function propertyHtml(text){const entries=lines(text);if(!entries.length)return'<p class="empty-copy">No properties entered.</p>';return entries.map(line=>{const colon=line.indexOf(':');return colon>0?`<p class="property"><b>${esc(line.slice(0,colon))}.</b> ${esc(line.slice(colon+1).trim())}</p>`:`<p class="property">${esc(line)}</p>`}).join('')}
function cumulativeStageText(item){if(item.stage==='none')return'';const parts=[];if(['dormant','awakened','exalted'].includes(item.stage)&&item.dormantProperties)parts.push(item.dormantProperties);if(['awakened','exalted'].includes(item.stage)&&item.awakenedProperties)parts.push(item.awakenedProperties);if(item.stage==='exalted'&&item.exaltedProperties)parts.push(item.exaltedProperties);return parts.join('\n')}
function artHtml(item){return item.artData?`<img src="${item.artData}" alt="${esc(item.name)} artwork">`:esc(item.icon||'✨')}
function playerIdentity(item){if(item.identification==='unidentified')return{name:item.unidentifiedName||'Unidentified Item',meta:'Unidentified magic item',appearance:item.unidentifiedText||item.appearance,properties:'',showStats:false};if(item.identification==='partial')return{name:item.name,meta:`${item.category} · Partially Identified`,appearance:item.appearance,properties:item.partialProperties,showStats:false};return{name:item.name,meta:`${item.category} · ${item.rarity}`,appearance:item.appearance,properties:[item.properties,cumulativeStageText(item)].filter(Boolean).join('\n'),showStats:true}}
function footer(item){return`<div class="item-footer"><span>${esc(item.ruleset||'Homebrew')}</span><span>${item.owner?`Owner: ${esc(item.owner)}`:esc(item.campaign||'Unassigned')}</span></div>`}
function frontCard(item,{print=false}={}){const view=playerIdentity(item),template=item.template||'detailed';return`<article class="item-card ${esc(template)} front"><div class="item-header"><div class="knowledge">${esc(item.identification||'identified')}</div><h3 class="item-name">${esc(view.name||'Unnamed Magic Item')}</h3><p class="item-meta">${esc(view.meta)}</p>${item.identification==='identified'?`<p class="item-meta">${esc(item.attunement||'')}</p>`:''}</div><div class="item-art">${artHtml(item)}</div>${view.appearance?`<p class="item-description">${esc(view.appearance)}</p>`:''}${item.description&&item.identification==='identified'?`<p>${esc(item.description)}</p>`:''}<div class="properties">${propertyHtml(view.properties)}${view.showStats&&item.stage!=='none'?`<div class="stage-banner">${esc(item.stage)} stage</div>`:''}${view.showStats&&item.activation?`<p class="property"><b>Activation.</b> ${esc(item.activation)}</p>`:''}${view.showStats&&item.charges?`<p class="property"><b>Charges.</b> ${esc(item.charges)}</p>`:''}${view.showStats&&item.recharge?`<p class="property"><b>Recharge.</b> ${esc(item.recharge)}</p>`:''}${view.showStats&&item.damage?`<p class="property"><b>Damage / Healing.</b> ${esc(item.damage)}</p>`:''}${view.showStats&&item.save?`<p class="property"><b>Save / Attack.</b> ${esc(item.save)}</p>`:''}</div>${footer(item)}${print?'<span class="cut-label">CUT</span>':''}</article>`}
function backCard(item,{dm=false,print=false}={}){const template=item.template||'detailed';return`<article class="item-card ${esc(template)} back ${dm?'dm':''}"><div class="item-header"><div class="knowledge">${dm?'Dungeon Master Copy':'Player Reference'}</div><h3 class="item-name">${esc(item.name||'Unnamed Magic Item')}</h3><p class="item-meta">${esc(item.category)} · ${esc(item.rarity)}</p></div><div class="back-mark">${esc(item.icon||'✨')}</div><div class="properties">${item.backText?propertyHtml(item.backText):'<p class="empty-copy">No back-card instructions entered.</p>'}${dm?`<p class="property"><b>Current identification.</b> ${esc(item.identification)}</p><p class="property"><b>Current stage.</b> ${esc(item.stage)}</p>${item.secret?`<div class="secret">${esc(item.secret)}</div>`:''}`:''}</div>${footer(item)}${print?'<span class="cut-label">CUT</span>':''}</article>`}
function renderPreview(){const item=values();let html,label;if(previewMode==='player-back'){html=backCard(item);label='Player Back'}else if(previewMode==='dm-back'){html=backCard(item,{dm:true});label='DM Back · Secrets Visible'}else{html=frontCard(item);label=`Player Front · ${item.identification.replace(/^./,x=>x.toUpperCase())}`}preview.innerHTML=html;document.getElementById('previewModeLabel').textContent=label;document.getElementById('saveState').textContent=editingId?'Editing saved item':'Unsaved draft';document.getElementById('saveState').classList.toggle('saved',Boolean(editingId))}
function fillForm(item){const normalized=normalize(item);editingId=normalized.id;artworkData=normalized.artData||'';[...form.elements].forEach(element=>{if(element.name&&normalized[element.name]!==undefined)element.value=normalized[element.name]});renderPreview();window.scrollTo({top:0,behavior:'smooth'})}
function saveItem(){const item=values();const index=library.findIndex(x=>x.id===item.id);if(index>=0)library[index]=item;else library.unshift(item);editingId=item.id;persist();refreshLibrary();renderPreview();toast('Magic item saved to this browser.')}
function blankItem(){editingId=null;artworkData='';form.reset();form.elements.template.value='detailed';form.elements.category.value='Wondrous Item';form.elements.rarity.value='Uncommon';form.elements.attunement.value='No attunement required';form.elements.ruleset.value='Homebrew';form.elements.identification.value='identified';form.elements.stage.value='none';form.elements.icon.value='✨';renderPreview()}
function duplicateItem(itemId){const source=library.find(x=>x.id===itemId);if(!source)return;const copy={...source,id:id(),name:`${source.name} — Copy`,updatedAt:Date.now()};library.unshift(copy);persist();refreshLibrary()}
function deleteItem(itemId){if(!confirm('Delete this saved item?'))return;library=library.filter(x=>x.id!==itemId);if(editingId===itemId)editingId=null;persist();refreshLibrary();renderPreview()}
function campaigns(){return[...new Set(library.map(x=>x.campaign||'Unsorted'))].sort((a,b)=>a.localeCompare(b))}
function refreshCampaignControls(){const list=campaigns();campaignFilter.innerHTML='<option value="all">All campaigns</option>'+list.map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join('');document.getElementById('campaignNames').innerHTML=list.map(name=>`<option value="${esc(name)}"></option>`).join('');document.getElementById('campaignSummary').innerHTML=list.map(name=>`<span class="campaign-chip">${esc(name)} · ${library.filter(x=>(x.campaign||'Unsorted')===name).length}</span>`).join('')}
function renderLibrary(){const filter=campaignFilter.value||'all';const visible=library.filter(item=>filter==='all'||(item.campaign||'Unsorted')===filter);if(!visible.length){libraryGrid.innerHTML='<p class="empty-copy">No saved items in this campaign folder.</p>';return}libraryGrid.innerHTML=visible.map(item=>`<article class="library-item"><label class="select-row"><input type="checkbox" data-select="${item.id}"><b>Select for duplex sheet</b></label><h3>${esc(item.name)}</h3><div class="library-meta">${esc(item.campaign||'Unsorted')} · ${esc(item.rarity)} · ${esc(item.identification)} · ${esc(item.stage)}</div><div class="library-actions"><button class="btn light" data-edit="${item.id}">Edit</button><button class="btn light" data-copy="${item.id}">Duplicate</button><button class="btn danger" data-delete="${item.id}">Delete</button></div></article>`).join('');$$('[data-edit]').forEach(button=>button.onclick=()=>fillForm(library.find(x=>x.id===button.dataset.edit)));$$('[data-copy]').forEach(button=>button.onclick=()=>duplicateItem(button.dataset.copy));$$('[data-delete]').forEach(button=>button.onclick=()=>deleteItem(button.dataset.delete))}
function refreshLibrary(){const selected=campaignFilter.value;refreshCampaignControls();if(campaigns().includes(selected))campaignFilter.value=selected;renderLibrary()}
function duplexBackOrder(items){const output=[];for(let i=0;i<items.length;i+=3)output.push(...items.slice(i,i+3).reverse());return output}
function slots(items,side,dm=false){return items.map(item=>`<div class="print-slot">${side==='front'?frontCard(item,{print:true}):backCard(item,{dm,print:true})}</div>`).join('')}
function buildPrint(items,{duplex=true,dmBack=false}={}){if(items.length===1&&items[0].template==='artifact'){const item=items[0],pages=[`<section class="artifact-page">${slots([item],'front')}</section>`];if(duplex)pages.push(`<section class="artifact-page">${slots([item],'back',dmBack)}</section>`);printSheet.innerHTML=pages.join('');window.print();return}const pages=[];for(let i=0;i<items.length;i+=9){const group=items.slice(i,i+9);pages.push(`<section class="print-page">${slots(group,'front')}</section>`);if(duplex)pages.push(`<section class="print-page">${slots(duplexBackOrder(group),'back',dmBack)}</section>`)}printSheet.innerHTML=pages.join('');window.print()}
function printCurrent(duplex){buildPrint([values()],{duplex})}
function printCurrentDm(){buildPrint([values()],{duplex:true,dmBack:true})}
function printSelected(){const selected=$$('[data-select]:checked').map(box=>library.find(item=>item.id===box.dataset.select)).filter(Boolean);if(!selected.length){alert('Select at least one saved item first.');return}buildPrint(selected,{duplex:true})}
function exportLibrary(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),items:library},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='dm-forge-magic-items.json';anchor.click();URL.revokeObjectURL(url)}
function importLibrary(file){const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result),items=Array.isArray(parsed)?parsed:parsed.items;if(!Array.isArray(items))throw new Error('No item list found.');const map=new Map(library.map(item=>[item.id,item]));items.map(normalize).forEach(item=>map.set(item.id,item));library=[...map.values()];persist();refreshLibrary();toast('Magic item library imported.')}catch(error){alert(`Import failed: ${error.message}`)}};reader.readAsText(file)}
function resizeArtwork(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);artworkData=canvas.toDataURL('image/jpeg',.84);renderPreview()};image.onerror=()=>alert('That image could not be read.');image.src=reader.result};reader.readAsDataURL(file)}
function loadClericBox(){fillForm({...CLERIC_BOX,id:id()});editingId=null;document.getElementById('saveState').textContent='Showcase loaded — save to keep it';toast('Cleric in a Box loaded into the editor.')}
function toast(message){const element=document.createElement('div');element.textContent=message;element.style='position:fixed;z-index:100;left:50%;bottom:20px;transform:translateX(-50%);background:#281713;color:#fff4ce;padding:12px 18px;border:1px solid #d4a64c;border-radius:8px;max-width:90vw;box-shadow:0 8px 30px #0008';document.body.append(element);setTimeout(()=>element.remove(),2800)}
function $$(selector){return[...document.querySelectorAll(selector)]}

form.addEventListener('input',()=>{if(editingId)document.getElementById('saveState').textContent='Edited — save changes';renderPreview()});
document.getElementById('artUpload').addEventListener('change',event=>resizeArtwork(event.target.files[0]));
document.getElementById('removeArt').onclick=()=>{artworkData='';document.getElementById('artUpload').value='';renderPreview()};
document.getElementById('saveItem').onclick=saveItem;
document.getElementById('newItem').onclick=blankItem;
document.getElementById('loadClericBox').onclick=loadClericBox;
document.getElementById('playerFront').onclick=()=>{previewMode='player-front';renderPreview()};
document.getElementById('playerBack').onclick=()=>{previewMode='player-back';renderPreview()};
document.getElementById('dmBack').onclick=()=>{previewMode='dm-back';renderPreview()};
document.getElementById('printFront').onclick=()=>printCurrent(false);
document.getElementById('printDuplex').onclick=()=>printCurrent(true);
document.getElementById('printDm').onclick=printCurrentDm;
document.getElementById('printSelected').onclick=printSelected;
document.getElementById('exportLibrary').onclick=exportLibrary;
document.getElementById('importLibrary').onchange=event=>event.target.files[0]&&importLibrary(event.target.files[0]);
campaignFilter.onchange=renderLibrary;
refreshLibrary();renderPreview();
