export function productJsonLd(product) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: product.title,
    description: product.description || 'Printable tabletop monster cards generated by Monster Card Forge.',
    brand: {
      '@type': 'Brand',
      name: 'Monster Card Forge',
    },
    category: 'Tabletop roleplaying game accessory',
    offers: product.priceTier === 'free'
      ? undefined
      : {
          '@type': 'Offer',
          availability: 'https://schema.org/PreOrder',
          priceCurrency: 'USD',
        },
  };
}

export function pageMeta({ title, description }) {
  return { title, description };
}
